/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_after 5829 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_after 5829 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_also 2197 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_also 2197 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_although 425 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_although 425 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_and 104735 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_and 104735 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_as 10741 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_as 10741 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_at_that_time 23 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_at_that_time 23 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_at_the_same_time 189 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_at_the_same_time 189 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_at_the_time 54 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_at_the_time 54 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_but 29926 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_but 29926 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_earlier 655 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_earlier 655 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_even_though 211 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_even_though 211 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_first 4020 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_first 4020 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_for 70344 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_for 70344 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_further 90 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_further 90 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_comparison 8 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_comparison 8 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_fact 76 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_fact 76 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_particular 22 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_particular 22 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_return 9 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_return 9 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_short 21 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_short 21 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_sum 3 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_sum 3 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_the_end 99 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_the_end 99 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_turn 8 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_in_turn 8 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_instead 874 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_instead 874 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_later 2112 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_later 2112 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_nevertheless 15 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_nevertheless 15 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_next 5822 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_next 5822 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_nonetheless 10 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_nonetheless 10 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_now 22476 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_now 22476 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_on_the_other_hand 41 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_on_the_other_hand 41 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_on_the_whole 14 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_on_the_whole 14 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_or 10085 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_or 10085 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_plus 613 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_plus 613 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_rather 848 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_rather 848 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_regardless 35 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_regardless 35 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_second 1127 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_second 1127 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_so 41042 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_so 41042 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_soon 4914 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_soon 4914 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_still 8027 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_still 8027 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_that_is 1587 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_that_is 1587 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_then 8409 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_then 8409 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_third 225 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_third 225 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_though 4840 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_though 4840 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_thus 85 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_thus 85 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_what_'s_more 3 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_what_'s_more 3 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_when 12106 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_when 12106 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_while 3337 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_while 3337 --numTest 5000 --tokenizer pair
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_yet 2961 --numTest 5000 --loadModel all_model
/home/chidey/PDTB/scikit/bin/python3.2 ./trainDiscourseSentiment.py tokens_yet 2961 --numTest 5000 --tokenizer pair
