java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_after > ../social_meaning/corenlp_test_tokens_after_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_also > ../social_meaning/corenlp_test_tokens_also_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_although > ../social_meaning/corenlp_test_tokens_although_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_and > ../social_meaning/corenlp_test_tokens_and_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_as > ../social_meaning/corenlp_test_tokens_as_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_at_that_time > ../social_meaning/corenlp_test_tokens_at_that_time_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_at_the_same_time > ../social_meaning/corenlp_test_tokens_at_the_same_time_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_at_the_time > ../social_meaning/corenlp_test_tokens_at_the_time_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_but > ../social_meaning/corenlp_test_tokens_but_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_earlier > ../social_meaning/corenlp_test_tokens_earlier_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_even_though > ../social_meaning/corenlp_test_tokens_even_though_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_first > ../social_meaning/corenlp_test_tokens_first_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_for > ../social_meaning/corenlp_test_tokens_for_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_further > ../social_meaning/corenlp_test_tokens_further_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_comparison > ../social_meaning/corenlp_test_tokens_in_comparison_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_fact > ../social_meaning/corenlp_test_tokens_in_fact_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_particular > ../social_meaning/corenlp_test_tokens_in_particular_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_return > ../social_meaning/corenlp_test_tokens_in_return_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_short > ../social_meaning/corenlp_test_tokens_in_short_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_sum > ../social_meaning/corenlp_test_tokens_in_sum_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_the_end > ../social_meaning/corenlp_test_tokens_in_the_end_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_in_turn > ../social_meaning/corenlp_test_tokens_in_turn_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_instead > ../social_meaning/corenlp_test_tokens_instead_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_later > ../social_meaning/corenlp_test_tokens_later_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_nevertheless > ../social_meaning/corenlp_test_tokens_nevertheless_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_next > ../social_meaning/corenlp_test_tokens_next_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_nonetheless > ../social_meaning/corenlp_test_tokens_nonetheless_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_now > ../social_meaning/corenlp_test_tokens_now_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_on_the_other_hand > ../social_meaning/corenlp_test_tokens_on_the_other_hand_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_on_the_whole > ../social_meaning/corenlp_test_tokens_on_the_whole_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_or > ../social_meaning/corenlp_test_tokens_or_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_plus > ../social_meaning/corenlp_test_tokens_plus_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_rather > ../social_meaning/corenlp_test_tokens_rather_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_regardless > ../social_meaning/corenlp_test_tokens_regardless_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_second > ../social_meaning/corenlp_test_tokens_second_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_so > ../social_meaning/corenlp_test_tokens_so_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_soon > ../social_meaning/corenlp_test_tokens_soon_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_still > ../social_meaning/corenlp_test_tokens_still_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_that_is > ../social_meaning/corenlp_test_tokens_that_is_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_then > ../social_meaning/corenlp_test_tokens_then_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_third > ../social_meaning/corenlp_test_tokens_third_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_though > ../social_meaning/corenlp_test_tokens_though_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_thus > ../social_meaning/corenlp_test_tokens_thus_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_when > ../social_meaning/corenlp_test_tokens_when_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_while > ../social_meaning/corenlp_test_tokens_while_prediction
java -cp "lib/*" -mx5g edu.stanford.nlp.sentiment.SentimentPipeline -file ../social_meaning/corenlp_test_tokens_yet > ../social_meaning/corenlp_test_tokens_yet_prediction
